### ISSUE TITLE
Composer installs error in symfony 4.2+

### ISSUE THREAD

**Issue by xavierkaitha94** [GeniusesOfSymfony/WebSocketBundle#365] opened 2019-02-06 06:18 UTC
While installing composer it returns error in symfony 4.2 +,
Following is error, please have a look,

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In GosWebSocketExtension.php line 210:
!!                                     
!!    Notice: Undefined index: server  
!!

**Comment by mbabker** [comment] 2019-02-06 13:21
Duplicate of #358

**Closed by mbabker** 2019-02-06 13:21 UTC
